import { colors } from 'src/contexts/theme/colors';
import { css } from 'styled-components';

export const palette = {
	palette01: {
		dark: {
			background: colors.charlestonGreen,
			backgroundHover: colors.outerSpace,
			title: colors.white,
			primary: colors.brandeisBlue,
			textColorPrimary: colors.white,
			textPrimary: colors.white,
			secondary: colors.white,
			placeholder: colors.manatee,
			shadow:
				'rgb(0 0 0 / 10%) 0px 1px 3px 0px, rgb(0 0 0 / 6%) 0px 1px 2px 0px',
			fadedShadow: `0px 22px 119px 0px ${colors.outerSpace75}`,
			error: colors.red,
			buttonText: colors.white,
			terminal: css`#333`,
			scanline: 'rgba(136, 192, 208, 0.03)',
		},
		light: {
			background: '#F5F8FF',
			backgroundHover: '#FFFFFF',
			title: '#546E7A',
			primary: '#7B9EBD',
			textColorPrimary: '#FFFFFF',
			textPrimary: '#FFFFFF',
			secondary: '#748893',
			placeholder: '#A5B7C2',
			shadow: '20px 20px 60px #bebebe, -20px -20px 60px #ffffff',
			fadedShadow: `0px 22px 119px 0px ${colors.white75}`,
			error: colors.red,
			buttonText: '#3F5A6C',
			windowBg: '#EFF5FB',
			buttonFace: '#E4EBF1',
			buttonHighlight: '#FFFFFF',
			buttonShadow: '#C8D5DF',
			windowHeader: '#7B9EBD',
			terminal: css`#f5f5f5`,
			scanline: 'rgba(136, 192, 208, 0.03)',
			glowText: '#7B9EBD',
		},
	},
	palette02: {
		dark: {
			background: '',
			backgroundHover: '',
			title: '',
			primary: '',
			textColorPrimary: '',
			textPrimary: '',
			secondary: '',
			placeholder: '',
			shadow: '',
			fadedShadow: '',
			error: '',
			terminal: css`#333`,
			scanline: 'rgba(136, 192, 208, 0.03)',
		},
		light: {
			background: '',
			backgroundHover: '',
			title: '',
			primary: '',
			textColorPrimary: '',
			textPrimary: '',
			secondary: '',
			placeholder: '',
			shadow: '',
			fadedShadow: '',
			error: '',
			terminal: css`#f5f5f5`,
			scanline: 'rgba(136, 192, 208, 0.03)',
		},
	},
	// Minimalist Y2K palette
	y2k: {
		dark: {
			background: colors.y2k.dark.background,
			backgroundHover: colors.softBlack,
			title: colors.white,
			primary: colors.y2k.dark.accent1,
			textColorPrimary: colors.white,
			textPrimary: colors.white,
			secondary: colors.white,
			placeholder: colors.y2k.dark.textAlt,
			shadow: '0px 2px 4px rgba(0, 0, 0, 0.2)',
			fadedShadow: '0px 4px 8px rgba(0, 0, 0, 0.1)',
			error: colors.red,
			buttonText: colors.white,
			terminal: css`#333`,
			scanline: 'rgba(136, 192, 208, 0.03)',
		},
		light: {
			background: colors.y2k.light.background,
			backgroundHover: colors.white,
			title: colors.softBlack,
			primary: colors.navy,
			textColorPrimary: colors.white,
			textPrimary: colors.white,
			secondary: colors.softBlack,
			placeholder: colors.gray,
			shadow: '0px 2px 4px rgba(0, 0, 0, 0.1)',
			fadedShadow: '0px 4px 8px rgba(200, 200, 200, 0.2)',
			error: colors.red,
			buttonText: colors.softBlack,
			terminal: css`#f5f5f5`,
			scanline: 'rgba(136, 192, 208, 0.03)',
		},
	},
	// Windows 98 palette
	win98: {
		dark: {
			background: colors.win98.desktop,
			backgroundHover: colors.win98.buttonShadow,
			title: colors.win98.activeTitleText,
			primary: colors.win98.activeTitle,
			textColorPrimary: colors.win98.activeTitleText,
			textPrimary: colors.win98.activeTitleText,
			secondary: colors.white,
			placeholder: colors.white,
			shadow:
				'inset -1px -1px #0a0a0a, inset 1px 1px #ffffff, inset -2px -2px grey, inset 2px 2px #dfdfdf',
			innerShadow:
				'inset -1px -1px #ffffff, inset 1px 1px #0a0a0a, inset -2px -2px #dfdfdf, inset 2px 2px grey',
			error: colors.red,
			windowBg: colors.win98.windowBg,
			buttonFace: colors.win98.buttonFace,
			buttonHighlight: colors.win98.buttonHighlight,
			buttonShadow: colors.win98.buttonShadow,
			buttonText: colors.win98.buttonText,
			windowHeader: colors.win98.windowHeader,
			windowFrame: colors.win98.windowFrame,
			terminal: css`#000080`,
			scanline: 'rgba(136, 192, 208, 0.03)',
			terminalText: colors.win98.terminalText,
			terminalPrompt: colors.win98.terminalPrompt,
			terminalCommand: colors.win98.terminalCommand,
		},
		light: {
			background: colors.win98.desktop,
			backgroundHover: colors.win98.buttonShadow,
			title: colors.win98.activeTitleText,
			primary: colors.win98.activeTitle,
			textColorPrimary: colors.win98.activeTitleText,
			textPrimary: colors.win98.activeTitleText,
			secondary: colors.win98.buttonText,
			placeholder: colors.win98.buttonText,
			shadow:
				'inset -1px -1px #0a0a0a, inset 1px 1px #ffffff, inset -2px -2px grey, inset 2px 2px #dfdfdf',
			innerShadow:
				'inset -1px -1px #ffffff, inset 1px 1px #0a0a0a, inset -2px -2px #dfdfdf, inset 2px 2px grey',
			error: colors.red,
			windowBg: colors.win98.windowBg,
			buttonFace: colors.win98.buttonFace,
			buttonHighlight: colors.win98.buttonHighlight,
			buttonShadow: colors.win98.buttonShadow,
			buttonText: colors.win98.buttonText,
			windowHeader: colors.win98.windowHeader,
			windowFrame: colors.win98.windowFrame,
			terminal: css`#000080`,
			scanline: 'rgba(136, 192, 208, 0.03)',
			terminalText: colors.win98.terminalText,
			terminalPrompt: colors.win98.terminalPrompt,
			terminalCommand: colors.win98.terminalCommand,
		},
	},
	// Cyberpunk palette
	cyberpunk: {
		dark: {
			background: colors.cyberBlack,
			backgroundHover: colors.cyberDarkBlue,
			title: colors.white,
			primary: colors.neonBlue,
			textColorPrimary: colors.white,
			textPrimary: colors.white,
			secondary: colors.white,
			placeholder: colors.neonBlue,
			shadow:
				'0 0 10px #FF00FF, 0 0 20px #FF00FF, 0 0 30px #FF00FF, 0 0 40px #FF00FF',
			innerShadow: '0 0 5px #00FFFF inset, 0 0 10px #00FFFF inset',
			fadedShadow: '0 0 15px rgba(255, 0, 255, 0.7)',
			error: colors.red,
			windowBg: colors.cyberBlack,
			buttonFace: colors.cyberDarkBlue,
			buttonHighlight: colors.neonBlue,
			buttonShadow: colors.cyberBlack,
			buttonText: colors.white,
			windowHeader: colors.neonPurple,
			windowFrame: colors.neonPink,
			accent1: colors.neonPink,
			accent2: colors.neonBlue,
			accent3: colors.neonGreen,
			accent4: colors.electricBlue,
			glowText: colors.neonPink,
			textGlow: '0 0 5px #FF00FF, 0 0 10px #FF00FF',
			terminal: css`#0a0a16`,
			scanline: 'rgba(0, 255, 255, 0.05)',
		},
		light: {
			background: colors.cyberDarkBlue,
			backgroundHover: colors.cyberNightPurple,
			title: colors.white,
			primary: colors.neonPink,
			textColorPrimary: colors.white,
			textPrimary: colors.white,
			secondary: colors.white,
			placeholder: colors.neonYellow,
			shadow:
				'0 0 10px #00FFFF, 0 0 20px #00FFFF, 0 0 30px #00FFFF, 0 0 40px #00FFFF',
			innerShadow: '0 0 5px #FF00FF inset, 0 0 10px #FF00FF inset',
			fadedShadow: '0 0 15px rgba(0, 255, 255, 0.7)',
			error: colors.red,
			windowBg: colors.cyberNightPurple,
			buttonFace: colors.cyberDarkBlue,
			buttonHighlight: colors.neonPink,
			buttonShadow: colors.cyberBlack,
			buttonText: colors.white,
			windowHeader: colors.neonBlue,
			windowFrame: colors.electricBlue,
			accent1: colors.neonBlue,
			accent2: colors.neonPink,
			accent3: colors.neonYellow,
			accent4: colors.matrixGreen,
			glowText: colors.neonBlue,
			textGlow: '0 0 5px #00FFFF, 0 0 10px #00FFFF',
			terminal: css`#0a0a16`,
			scanline: 'rgba(0, 255, 255, 0.05)',
		},
	},
};
